on: [push, pull_request]
name: aws
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: AWS login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: List files in S3 bucket
      run: make
